version: "3.7"

services:
  db_teastream:
    container_name: postgres_teastream
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - 5434:5432 # Изменили внешний порт
    volumes:
      - postgres_data_teastream:/var/lib/postgresql/data
    networks:
      - teastream-backend

  redis_teastream:
    container_name: redis_teastream
    image: redis:5.0
    restart: always
    ports:
      - 6380:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data_teastream:/data
    networks:
      - teastream-backend

volumes:
  postgres_data_teastream:
  redis_data_teastream:

networks:
  teastream-backend:
